/**
 * Just enough RFC 5322 header parsing for what the inbound path needs.
 *
 * The provider hands us a raw header block as one string. We need three things out of it —
 * `Message-ID`, `In-Reply-To`, `References` — plus the loop-guard headers. That does not
 * justify a MIME library: the whole of it is unfolding continuation lines and splitting on
 * the first colon.
 */

/**
 * Parses a raw header block into lowercased names → values.
 *
 * **Unfolding first.** RFC 5322 lets a long header wrap onto continuation lines that begin
 * with whitespace, and a `References:` chain routinely does. Splitting on newlines without
 * unfolding first would turn one header into several unparseable fragments and silently
 * lose the thread.
 *
 * On a repeated header, the **first** occurrence wins. Headers accumulate as a message is
 * relayed, so the earliest is the one closest to the original sender; taking the last
 * would prefer whatever the final hop bolted on.
 */
export function parseHeaderBlock(raw: string): Record<string, string> {
  if (!raw) return {}

  const unfolded = raw.replace(/\r?\n[ \t]+/g, ' ')
  const headers: Record<string, string> = {}

  for (const line of unfolded.split(/\r?\n/)) {
    const colon = line.indexOf(':')
    if (colon <= 0) continue

    const name = line.slice(0, colon).trim().toLowerCase()
    const value = line.slice(colon + 1).trim()

    if (name && headers[name] === undefined) headers[name] = value
  }

  return headers
}

/**
 * Normalises a Message-ID for storage and comparison: angle brackets stripped, lowercased.
 *
 * The domain part is case-insensitive and the local part is treated as such by every real
 * MTA, so lowercasing makes `In-Reply-To` lookups match what we stored — which is the
 * whole point of keeping them.
 */
export function normaliseMessageId(value: string | undefined | null): string | null {
  if (!value) return null

  const trimmed = value.trim().replace(/^</, '').replace(/>$/, '').trim().toLowerCase()
  return trimmed || null
}

/**
 * Every message id in a `References` or `In-Reply-To` value, in order.
 *
 * `References` is a space-separated chain of `<id>` tokens; `In-Reply-To` is normally one
 * but is permitted to hold several. Anything not inside angle brackets is ignored — some
 * clients append commentary, and a bare word is not an id.
 */
export function messageIdsFrom(value: string | undefined | null): string[] {
  if (!value) return []

  const ids: string[] = []
  for (const match of value.matchAll(/<([^<>\s]+)>/g)) {
    const id = normaliseMessageId(match[1])
    if (id) ids.push(id)
  }

  return ids
}

/**
 * Whether this message was generated by a machine rather than typed by a person.
 *
 * Out-of-office replies, bounce notices and mailing-list traffic must never become
 * tickets — and more importantly must never become *replies*, because our own
 * acknowledgement would then trigger theirs and the two systems would mail each other
 * until someone noticed.
 *
 * `Auto-Submitted` (RFC 3834) is the standard signal; the `X-Auto*` headers and
 * `Precedence` are what clients actually send in practice.
 */
export function isAutomatedMessage(headers: Record<string, string>): boolean {
  const autoSubmitted = headers['auto-submitted']?.toLowerCase()
  if (autoSubmitted && autoSubmitted !== 'no') return true

  if (headers['x-autoreply'] || headers['x-autorespond'] || headers['x-autoresponder']) {
    return true
  }

  const precedence = headers['precedence']?.toLowerCase()
  if (precedence && ['bulk', 'auto_reply', 'list', 'junk'].includes(precedence)) return true

  // Present on essentially every mailing list, and a list is not a requester.
  return Boolean(headers['list-id'] || headers['list-unsubscribe'])
}
